"""Updated User model to handle salt explicitly

Revision ID: 065ab7a852dd
Revises: fbec4b66b7a8
Create Date: 2025-04-28 15:07:33.688468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065ab7a852dd'
down_revision = 'fbec4b66b7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
