"""empty message

Revision ID: 7e442efe8569
Revises: b3e76b1c594e
Create Date: 2025-05-01 04:14:03.797343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e442efe8569'
down_revision = 'b3e76b1c594e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
