"""Added master_salt to user table

Revision ID: b3e76b1c594e
Revises: e3523c849bce
Create Date: 2025-04-29 20:37:05.849469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e76b1c594e'
down_revision = 'e3523c849bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_salt', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('master_salt')

    # ### end Alembic commands ###
