"""Removed salt section in user table

Revision ID: e3523c849bce
Revises: 065ab7a852dd
Create Date: 2025-04-28 15:10:19.110209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3523c849bce'
down_revision = '065ab7a852dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
