"""Added encryption fields to Passwords model

Revision ID: fbec4b66b7a8
Revises: 06fbd6d08e91
Create Date: 2025-04-20 18:10:02.676817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec4b66b7a8'
down_revision = '06fbd6d08e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_password', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('iv', sa.String(length=64), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('iv')
        batch_op.drop_column('salt')
        batch_op.drop_column('encrypted_password')

    # ### end Alembic commands ###
